version: "3.7"
services:
  server: 
    build: 
      context: ./server
      dockerfile: Dockerfile.server
    restart: always
    ports: 
      - "8081:8081"
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.client
    restart: always
    ports:
      - "8080:80"
    depends_on: 
      - server
